baseURL = 'http://localhost:1313/'
languageCode = 'pl'
title = 'Iga Dietetyk'

[taxonomies]
  category = ''
  tag = ''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'Iga Dietetyk - Schudnij raz na zawsze'